# -*- coding: utf-8 -*-
"""Challenge.ipynb

Automatically generated by Colab.

Original file was a Jupyter Notebook. This is the Python code version for ease
The Jupyter Notebook can be viewed here: https://gist.github.com/cararm4073/d8d94ebe0958a6807f75b6afdf1f803b

#Import libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf
import scipy.stats as ss
import math
import seaborn as sns
import sklearn as sk

"""#Loading the CSV file
From github
"""

file = "https://raw.githubusercontent.com/cararm4073/finalProyects1/refs/heads/main/MA1042/FPdata.csv"

df = pd.read_csv(file, index_col=0)

"""#I	Supervised Learning

##Deleting empty and duplicate rows

###Before
"""

df.head()

df.info()

df.dropna(inplace=True)
df.drop_duplicates(inplace=True)

"""###After"""

df.head()

df.info()

"""---
##**Outliers and boxplots**

###Before taking the outliers
"""

fig, ax = plt.subplots(1,3,figsize=(13,4))
for i_n,i_v in enumerate(df.columns):
  ax[i_n].boxplot(df[i_v],whis=1.2)
  ax[i_n].set_title(i_v)

"""###Taking the outliers out"""

def my_outliers1(df, column, k=1.2):
  """
  Given a dataframe df and a string find the indeces for which we have an outlier in a boxplot with whishers of size 1.2*IQR
  """
  Q1 = np.quantile(df[column], 0.25)
  Q3 = np.quantile(df[column], 0.75)
  IQR = Q3 - Q1

  top = Q3 + k * IQR
  bottom = Q1 - k * IQR

  outliers = []

  for i in df.index:
    if df[column][i] < bottom or df[column][i] > top:
      outliers.append(i)
  return outliers

"""Detect and delete outliers"""

def my_outliers2(df, columns):
  """
  Given a dataframe df and a list of string columns, find the indeces for which we have outliers in either of the columns using 1.2*IQR for the outliers.
  """
  outliers = []
  for column in columns:
    outliers = outliers + my_outliers1(df, column)
  return outliers

"""Outliers indexes"""

outliers = my_outliers2(df, columns = list(df.columns))
outliers

df.drop(outliers, inplace = True)
df.shape

"""Boxplots without outliers"""

df.head()

df.info()

fig,ax = plt.subplots(1,3, figsize=(13, 4))
for i_n,i_v in enumerate(df.columns):
  ax[i_n].boxplot(df[i_v],whis=1.2)
  ax[i_n].set_title(i_v)

"""##Linear regression"""

df.columns

model = smf.ols("FP ~ BMI + AGE", data = df)
results= model.fit()

residuals = results.resid
fittedvalues = results.fittedvalues
order = list(range(len(residuals)))

print(results.summary2())

"""##Significant variables

According to the p-values ​​obtained in the linear regression, both BMI and AGE variables are significant variables for predicting FP, since both have p-values ​​of 0.

##4-in-1 Graph
Data from linear regression
"""

fig, ax = plt.subplots(2,2, figsize= (8,6))
ax[0,0].hist(residuals)
ax[0,0].set_title('Histogram of Residuals')
ax[0,1].scatter(fittedvalues, residuals)
ax[0,1].set_title('Residuals vs Fitted values')
ax[1,1].scatter(order, residuals)
ax[1,1].set_title('Residuals vs Order')
ss.probplot(residuals, plot = ax[1,0])
fig.tight_layout()
fig.show()

"""#II	Unsupervised Learning

##Clustering Algorithm DBSCAN
"""

model_db = sk.cluster.DBSCAN(eps= 2.5, min_samples=5)
results_db = model_db.fit_predict(df)
results_db
colors_db = ['blue' if i==0 else
        'red' if i==1 else
        'black'
        for i in results_db]
df['cluster'] = results_db

"""##Making 2 groups from the cluster"""

df.head(3)

group1 = df[df['cluster']==0]
group2 = df[df['cluster']==1]

"""##General graph of clusters, after DBSCAN"""

fig, ax = plt.subplots(1,2, figsize= (8,6))
ax[0].scatter(fittedvalues, residuals, color = colors_db)
ax[0].set_title('Residuals vs Fitted values')
ax[1].scatter(order, residuals, color = colors_db)
ax[1].set_title('Residuals vs Order')
fig.show()

"""##Linear regression 1 after DBSCAN"""

group1.head(3)

model1 = smf.ols('FP ~ BMI + AGE', data = group1)
results1 = model1.fit()
residuals1 = results1.resid
fittedvalues1 = results1.fittedvalues
order1 = list(range(len(residuals1)))

print(results1.summary2())

"""###Graphs of the new linear regression"""

fig, ax = plt.subplots(2,2, figsize= (8,6))
ax[0,0].hist(residuals1)
ax[0,0].set_title('histogram or residuals1')
ax[0,1].scatter(fittedvalues1, residuals1)
ax[0,1].set_title('residuals1 vs fitted values1')
ax[1,1].scatter(order1, residuals1)
ax[1,1].set_title('residuals1 vs order1')
ss.probplot(residuals1, plot = ax[1,0])
fig.tight_layout()
fig.show()

"""##Linear regression 2 after DBSCAN"""

group2.head(3)

model2 = smf.ols('FP ~ BMI + AGE', data = group2)
results2 = model2.fit()
residuals2 = results2.resid
fittedvalues2 = results2.fittedvalues
order2 = list(range(len(residuals2)))

print(results2.summary2())

"""###Graphs of linear regression"""

fig, ax = plt.subplots(2,2, figsize= (8,6))
ax[0,0].hist(residuals2)
ax[0,0].set_title('histogram or residuals2')
ax[0,1].scatter(fittedvalues2, residuals2)
ax[0,1].set_title('residuals1 vs fitted values1')
ax[1,1].scatter(order2, residuals2)
ax[1,1].set_title('residuals1 vs order1')
ss.probplot(residuals2, plot = ax[1,0])
fig.tight_layout()
fig.show()