# -*- coding: utf-8 -*-
"""Problem situation MA1031.335.ipynb

Automatically generated by Colab.

The original Notebook files can be seen here: https://gist.github.com/cararm4073/9a945ec9a3fd868338d1229b7daeaf47

# Load libraries
"""

import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np


"""# Load file and data frame"""

df = pd.read_csv("https://raw.githubusercontent.com/cararm4073/tec-archive/refs/heads/main/university/EF26/MA1031/Basededatos_SituacionProblemaE1.csv")
df.columns = df.columns.str.strip() #clean the columns

#remove the $ sign from the column so that we can use numbers and not text vars
df['Price'] = (df['Price']
                            .astype(str)
                            .str.replace('$', '', regex=False)
                            .str.replace(',', '', regex=False)
                            .str.strip()
                            .astype(float))

"""# 1. Scatter plot (age and price)"""

plt.figure(figsize=(10, 5.5))
sns.scatterplot(data=df1, x='Age', y='Price', label='Sold car')

sns.regplot(
    data=df1,
    x='Age',
    y='Price',
    ci=None,
    line_kws={'color':'red', 'linewidth':2,
    'label': 'Tendency line'}
)
plt.title('Scatter plot: Age vs Sale price')
plt.xlabel('Age (years)')
plt.ylabel('Sale price (pesos)')
plt.legend()
plt.grid(True)
plt.plot()

"""# 2. Scatter plot (miles and price)"""

plt.figure(figsize=(10, 5.5))
sns.regplot(
    data=df1,
    x='Miles',
    y='Price',
    ci=None,
    line_kws={'color':'red', 'linewidth':2,
    'label': 'Tendency line'}
)
sns.scatterplot(data=df1, x='Miles', y='Price')
plt.title('Scatter plot: Miles vs Sales price')
plt.xlabel('Miles')
plt.ylabel('Sale price (pesos)')
plt.legend()
plt.grid(True)
plt.plot()

"""# 3. Linear regression (age and miles)
Fit a multiple linear regression model to estimate the selling price based on age and mileage
"""

X1 = df[['Age', 'Miles']]
X1 = sm.add_constant(X1) #add constant
y = df['Price']

model1 = sm.OLS(y, X1).fit()
print("\n--- Regression model (Age and miles) ---\n\n")
print(model1.summary())

"""# 4. Linear regression (all variables)
Fit a multiple linear regression model considering all provided variables
"""

X2 = df[['Age', 'Miles', 'Condition', 'Excellent', 'Owner']]
X2 = sm.add_constant(X2)
y  = df['Price']

model2 = sm.OLS(y, X2).fit()
print("\n--- Regression model (All variables) ---\n\n")
print(model2.summary())

"""___
# Part 2 (Multiple linear regression)

## Scatter plot of the data
"""

# @title
df2 = pd.read_csv("https://raw.githubusercontent.com/cararm4073/tec-archive/refs/heads/main/university/EF26/MA1031/Basededatos_SituacionProblemaE2.csv")
sales = pd.concat([df2['Year 1'], df2['Year 2'], df2['Year 3']]).reset_index(drop=True)
time = np.arange(1, len(sales) + 1)

fig, ax = plt.subplots(figsize=(12, 6))

ax.scatter(time, sales, color='blue', edgecolor='black', label='Sales data', s=80)
ax.plot(time, sales, color='dodgerblue', alpha=0.25, linestyle='-')

# Formatting the plot
ax.set_title('Scatter Plot of Quarterly Car Sales')
ax.set_xlabel('Time Period (Quarters, t=1 to 12)')
ax.set_ylabel('Cars sold')
ax.set_xticks(time)
ax.grid()
ax.legend(fontsize=11)
plt.plot()

print(df2)

"""## Formula of MLR

$$y' = \beta_0 + \beta_1 t + \beta_2 Q_1 + \beta_3 Q_2 + \beta_4 Q_3$$
"""

#create X matrix
Y = np.array(sales).reshape(-1,1)
print(Y)

sales = [3, 5, 8, 10, 4, 7, 9, 12, 6, 8, 10, 14]

X = np.array([
    [1,  1, 1, 0, 0], # Year 1,Q1
    [1,  2, 0, 1, 0], # year 1, Q2
    [1,  3, 0, 0, 1], # year 1, Q3
    [1,  4, 0, 0, 0], # year 1, Q4
    [1,  5, 1, 0, 0], # year 2,Q1
    [1,  6, 0, 1, 0], # year 2, Q2
    [1,  7, 0, 0, 1], # year 2, Q3
    [1,  8, 0, 0, 0], # year 2, Q4
    [1,  9, 1, 0, 0], # Year 3,Q1
    [1, 10, 0, 1, 0], # Year 3,Q2
    [1, 11, 0, 0, 1], # Year 3,Q3
    [1, 12, 0, 0, 0]  # Year 3,Q4
])

print(X)

#transpose of X
X_T = X.T
print(X_T)

#first left multiplication
X_T_X = X_T @ X
print(X_T_X)

#resulting inverse matrix
X_T_X_inv = np.linalg.inv(X_T_X)
print(X_T_X_inv)

#next part of the equation
X_T_Y = X_T @ Y
print(X_T_Y)

#coefficients of beta
beta = beta = X_T_X_inv @ X_T_Y
print(beta)

b0, b1, b2, b3, b4 = beta.flatten()

y_q1 = b0 + b1*(13) + b2*(1) + b3*(0) + b4*(0)
print(f"{y_q1:.3f}")

y_q2 = b0 + b1*(14) + b2*(0) + b3*(1) + b4*(0)
print(f"{y_q2:.3f}")

y_q3 = b0 + b1*(15) + b2*(0) + b3*(0) + b4*(1)
print(f"{y_q3:.3f}")

y_q4 = b0 + b1*(16) + b2*(0) + b3*(0) + b4*(0)
print(f"{y_q4:.3f}")

#plot of second delivery data
fig, ax = plt.subplots(figsize=(15, 6))

ax.scatter(time, sales, color='blue', edgecolor='black', label='Sales data', s=80)
ax.plot(time, sales, color='dodgerblue', alpha=0.25, linestyle='-')

ax.set_title('Scatter Plot of Quarterly Car Sales and the forecast')
ax.set_xlabel('Time Period Quarters')
ax.set_ylabel('Cars sold')
ax.set_xticks(time)
ax.grid()
ax.legend(fontsize=11)
plt.plot()

#another model was also tested. It can be seen on the gist link on top of this file.