# -*- coding: utf-8 -*-
"""Problem situation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fJR5vei8cxvhUzJQJdc-MXrcSl2qkEIj

# Load libraries
"""

import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns

"""# Load file and data frame"""

df = pd.read_csv("https://raw.githubusercontent.com/cararm4073/tec-archive/refs/heads/main/university/EF26/MA1031/Basededatos_SituacionProblemaE1.csv")
df.columns = df.columns.str.strip() #clean the columns

#remove the $ sign from the column so that we can use numbers and not text vars
df['Price'] = (df['Price']
                            .astype(str)
                            .str.replace('$', '', regex=False)
                            .str.replace(',', '', regex=False)
                            .str.strip()
                            .astype(float))

"""# 1. Scatter plot (age and price)"""

# @title
plt.figure(figsize=(8, 5))
sns.scatterplot(data=df, x='Age', y='Price')
plt.title('Scatter plot: Age vs Sale price')
plt.xlabel('Age(years)')
plt.ylabel('Sale price (pesos)')
plt.savefig('age_vs_price.png')
plt.plot()

"""## 1.2 Regression model
Pendiente definir qué modelo se usará!!!!
"""



"""# 2. Scatter plot (miles and price)"""

# @title
plt.figure(figsize=(8, 5))
sns.scatterplot(data=df, x='Miles', y='Price')
plt.title('Scatter plot: Miles vs Sales price')
plt.xlabel('Miles')
plt.ylabel('Sale price (Pesos)')
plt.savefig('miles_vs_price.png')
plt.plot()

"""## 2.2 Regression model
Pendiente definir qué modelo se usará!!!!
"""



"""# 3. Linear regression (age and miles)
Fit a multiple linear regression model to estimate the selling price based on age and mileage
"""

# @title
X1 = df[['Age', 'Miles']]
X1 = sm.add_constant(X1) #add constant
y = df['Price']

model1 = sm.OLS(y, X1).fit()
print("\n--- Regression model (Age and miles) ---\n\n")
print(model1.summary())

"""# 4. Linear regression (all variables)
Fit a multiple linear regression model considering all provided variables
"""

# @title
X2 = df[['Age', 'Miles', 'Condition', 'Excellent', 'Owner']]
X2 = sm.add_constant(X2)
y  = df['Price']

model2 = sm.OLS(y, X2).fit()
print("\n--- Regression model (All variables) ---\n\n")
print(model2.summary())