# -*- coding: utf-8 -*-
"""Challenge F1014B.ipynb

Automatically generated by Colab.
Most of the explanation and other stuff from the notebook was removed. Most of the stuff here is code.
Also, most of the comments explaining what the code does was removed. For reference, the original file is below.

Original file can be seen here: https://gist.github.com/cararm4073/2d6584d4a7a6acabf077f1c802fd5b98

"""

"""# Import modules"""

import math
import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

"""#Constants"""

gravity = -9.81
v_i = 0

"""#Ask for inputs from the user

These values will be used for the 3 stages
"""

# @title
#ask for inputs from the user for part 1
mass = float(input("Enter the mass of the gondola in kilograms: "))
y_i = float(input("\nEnter the starting height in meters: "))
k = float(input("\nEnter the value for the constant of magnetic braking in kg/s: "))
t_max = float(input('\nEnter a whole value for the time that the "simulation" will be run in seconds: '))

#part 2
height_braking = float(input("\n\nEnter the height where the magnetic braking starts in meters: "))

"""#Final velocity value

Formula of acceleration: a = g - (k/m) * v
"""

# @title
#print the final velocity value
v_f = (mass*gravity)/k
print(f"\nThe final velocity would be: {v_f:.3f} m/s")

"""___

# 🔺 Stage 1: Free fall

## Now the code...

###Differential equation definition
"""

# @title
#function that will use the scipy.integrate library later on. using vectors of both the current time (t) and a "state vector" that will have the height and speed at the given time
def dif_eq(t,y):
  #array structure
  position = y[0] #the height or position
  speed = y[1]    #the speed

  # differential equation for free fall
  # there is nothing extra, so its just gravity constant
  accel = gravity

  #return the derivatives dy/dt and dv/dt, corresponding to speed and acceleration at given time
  return [speed, accel]

"""###Define when the gondola reaches the ground"""


def hit_ground(t, y):
  return y[0] - height_braking  

hit_ground.terminal = True
hit_ground.direction = -1


"""###Solve the equation (simulation)"""

solution1 = solve_ivp(dif_eq, [0, t_max], [y_i, v_i], events=hit_ground, dense_output=True, max_step=0.05 )

time_data = solution1.t
height_data = solution1.y[0]
velocity_data = solution1.y[1]

accel_data = np.full_like(time_data, gravity)

"""## 🗒 Showing the results"""

print(f"Real time that it took the gondola to fall: {time_data[-1]:.3f} s")
print(f"The time you asked for the simulation: {t_max:.3f}")

print(f"\nSpeed when the gondola reached the floor: {velocity_data[-1]:.3f} m/s")

print(f"\nFinal acceleration: {accel_data[-1]:.3f} m/s")

"""## 📊 Plotting"""

#subplots will be used for ease of representation of all the plots
fig, axs = plt.subplots(2, 2, figsize=(15, 10))
fig.suptitle("Differential equation of the free fall")

#speed vs time
axs[0,0].set_title("Speed vs time")
axs[0,0].plot(time_data, velocity_data, color='g', label='Speed')
axs[0, 0].axhline(y=v_f, color='r', linestyle='--', label=f'Vf = {v_f:.3f} m/s')
axs[0,0].set_xlabel("Time (s)")
axs[0,0].set_ylabel("Speed (m/s)")
axs[0,0].grid(True)
axs[0,0].legend()

#acceleration vs time
axs[1,0].set_title("Acceleration vs time")
axs[1,0].plot(time_data, accel_data, color='b', label=f'Acceleration = {gravity} m/s²')
#axs[1,0].axhline(y=0, color='r', linestyle='--', label=f'Acceleration=0')
axs[1,0].set_xlabel("Time (s)")
axs[1,0].set_ylabel("Acceleration (m/s²)")
axs[1,0].grid(True)
axs[1,0].legend()

#speed vs height
axs[0,1].set_title("Speed vs height")
axs[0,1].plot(height_data, velocity_data, color='lime', label='Speed')
axs[0, 1].axhline(y=v_f, color='r', linestyle='--', label=f'Vf = {v_f:.3f} m/s')
axs[0,1].set_xlabel("Height (m)")
axs[0,1].set_ylabel("Speed (m/s)")
axs[0,1].grid(True)
axs[0,1].legend()

#acceleration vs height
axs[1,1].set_title("Acceleration vs height")
axs[1,1].plot(height_data, accel_data, color='cyan', label=f'Acceleration = {gravity} m/s²')
#axs[1,1].axhline(y=0, color='r', linestyle='--', label=f'Acceleration=0')
axs[1,1].set_xlabel("Height (m)")
axs[1,1].set_ylabel("Acceleration (m/s²)")
axs[1,1].grid(True)
axs[1,1].legend()


plt.show()

"""But the axis of x is wind of weirdly represented if we go from negative to 0 on the x vs height plots, so we can flip it..."""

# @title
#subplots will be used for ease of representation of all the plots
fig, axs = plt.subplots(2, 2, figsize=(15, 10))
fig.suptitle("Differential equation of the free fall")

#speed vs time
axs[0,0].set_title("Speed vs time")
axs[0,0].plot(time_data, velocity_data, color='g', label='Speed')
axs[0, 0].axhline(y=v_f, color='r', linestyle='--', label=f'Vf = {v_f:.3f} m/s')
axs[0,0].set_xlabel("Time (s)")
axs[0,0].set_ylabel("Speed (m/s)")
axs[0,0].grid(True)
axs[0,0].legend()

#acceleration vs time
axs[1,0].set_title("Acceleration vs time")
axs[1,0].plot(time_data, accel_data, color='b', label=f'Acceleration = {gravity} m/s²')
#axs[1,0].axhline(y=0, color='r', linestyle='--', label=f'Acceleration=0')
axs[1,0].set_xlabel("Time (s)")
axs[1,0].set_ylabel("Acceleration (m/s²)")
axs[1,0].grid(True)
axs[1,0].legend()

#speed vs height
axs[0,1].set_title("Speed vs height")
axs[0,1].plot(height_data, velocity_data, color='lime', label='Speed')
axs[0, 1].axhline(y=v_f, color='r', linestyle='--', label=f'Vf = {v_f:.3f} m/s')
axs[0,1].set_xlabel("Height (m)")
axs[0,1].set_ylabel("Speed (m/s)")
axs[0,1].grid(True)
axs[0,1].legend()
axs[0,1].set_xlim(y_i, 0)

#acceleration vs height
axs[1,1].set_title("Acceleration vs height")
axs[1,1].plot(height_data, accel_data, color='cyan', label=f'Acceleration = {gravity} m/s²')
#axs[1,1].axhline(y=0, color='r', linestyle='--', label=f'Acceleration=0')
axs[1,1].set_xlabel("Height (m)")
axs[1,1].set_ylabel("Acceleration (m/s²)")
axs[1,1].grid(True)
axs[1,1].legend()
axs[1,1].set_xlim(y_i, 0)


plt.show()

"""Either image of the 4 graphs has the exact values, simply the x axis on 2 of the plots were flipped.

___
# 🔺 Stage 2: Magnetic braking

##Values of stage 1
"""

t_i2 = solution1.t[-1]
y_i2 = solution1.y[0,-1]
v_i2 = solution1.y[1,-1]

"""##Now the code...

###Magnetic braking equation
Using Eddy currents formula
"""

def magnetic_braking(t, y):
    speed = y[1]
    accel = gravity - (k / mass) * speed

    return [speed, accel]

"""###Define when the gondola reaches the ground"""

def hit_ground2(t, y):
    return y[0] - 0.0

hit_ground2.terminal = True
hit_ground2.direction = -1

"""###Solve the equation"""

solution2 = solve_ivp(magnetic_braking, [t_i2, t_max], [y_i2, v_i2], events=hit_ground2, dense_output=True, max_step=0.05)

"""##🗒 Showing the results"""

print(f"Final velocity when the gondola reaches the ground: {solution2.y[1,-1]:.3f} m/s")

"""___
#🔺 Stage 3: Merge the data

## Concatenate arrays
"""

total_time = np.concatenate((solution1.t, solution2.t))
total_height = np.concatenate((solution1.y[0], solution2.y[0]))
total_velocity = np.concatenate((solution1.y[1], solution2.y[1]))

"""###Calculate again the acceleration
"""

acc_1 = np.full_like(solution1.t, gravity)
acc_2 = gravity - (k / mass) * solution2.y[1]
total_acceleration = np.concatenate((acc_1, acc_2))

"""##📊 Plotting"""

fig, axs = plt.subplots(2, 2, figsize=(15, 10))
fig.suptitle("Free Fall + Magnetic Braking")

#speed vs time
axs[0,0].set_title("Speed vs time")
axs[0,0].plot(total_time, total_velocity, color='g', label='Speed')
axs[0, 0].axhline(y=v_f, color='r', linestyle='--', label=f'Vf = {v_f:.3f} m/s')
axs[0,0].axvline(x=t_i2, color='orange', linestyle='--', label='Magnetic braking')
axs[0,0].set_xlabel("Time (s)")
axs[0,0].set_ylabel("Speed (m/s)")
axs[0,0].grid(True)
axs[0,0].legend()

#acceleration vs time
axs[1,0].set_title("Acceleration vs time")
axs[1,0].plot(total_time, total_acceleration, color='b', label='Acceleration')
#axs[1,0].axhline(y=0, color='r', linestyle='--', label=f'Acceleration=0')
axs[1,0].axvline(x=t_i2, color='orange', linestyle='--', label='Magnetic braking')
axs[1,0].set_xlabel("Time (s)")
axs[1,0].set_ylabel("Acceleration (m/s²)")
axs[1,0].grid(True)
axs[1,0].legend()

#speed vs height
axs[0,1].set_title("Speed vs height")
axs[0,1].plot(total_height, total_velocity, color='lime', label='Speed')
axs[0, 1].axhline(y=v_f, color='r', linestyle='--', label=f'Vf = {v_f:.3f} m/s')
axs[0,1].axvline(x=height_braking, color='orange', linestyle='--', label='Magnetic braking')
axs[0,1].set_xlabel("Height (m)")
axs[0,1].set_ylabel("Speed (m/s)")
axs[0,1].grid(True)
axs[0,1].legend()

#acceleration vs height
axs[1,1].set_title("Acceleration vs height")
axs[1,1].plot(total_height, total_acceleration, color='cyan', label='Acceleration')
#axs[1,1].axhline(y=0, color='r', linestyle='--', label=f'Acceleration=0')
axs[1,1].axvline(x=height_braking, color='orange', linestyle='--', label='Magnetic braking')
axs[1,1].set_xlabel("Height (m)")
axs[1,1].set_ylabel("Acceleration (m/s²)")
axs[1,1].grid(True)
axs[1,1].legend()


plt.show()

"""Again, the two plots on the right look kind of odd because of the x-axis, so we flip it."""

fig, axs = plt.subplots(2, 2, figsize=(15, 10))
fig.suptitle("Free Fall + Magnetic Braking")

#speed vs time
axs[0,0].set_title("Speed vs time")
axs[0,0].plot(total_time, total_velocity, color='g', label='Speed')
axs[0, 0].axhline(y=v_f, color='r', linestyle='--', label=f'Vf = {v_f:.3f} m/s')
axs[0,0].axvline(x=t_i2, color='orange', linestyle='--', label='Magnetic braking')
axs[0,0].set_xlabel("Time (s)")
axs[0,0].set_ylabel("Speed (m/s)")
axs[0,0].grid(True)
axs[0,0].legend()

#acceleration vs time
axs[1,0].set_title("Acceleration vs time")
axs[1,0].plot(total_time, total_acceleration, color='b', label='Acceleration')
#axs[1,0].axhline(y=0, color='r', linestyle='--', label=f'Acceleration=0')
axs[1,0].axvline(x=t_i2, color='orange', linestyle='--', label='Magnetic braking')
axs[1,0].set_xlabel("Time (s)")
axs[1,0].set_ylabel("Acceleration (m/s²)")
axs[1,0].grid(True)
axs[1,1].set_xlim(y_i, 0)
axs[1,0].legend()

#speed vs height
axs[0,1].set_title("Speed vs height")
axs[0,1].plot(total_height, total_velocity, color='lime', label='Speed')
axs[0, 1].axhline(y=v_f, color='r', linestyle='--', label=f'Vf = {v_f:.3f} m/s')
axs[0,1].axvline(x=height_braking, color='orange', linestyle='--', label='Magnetic braking')
axs[0,1].set_xlabel("Height (m)")
axs[0,1].set_ylabel("Speed (m/s)")
axs[0,1].grid(True)
axs[0,1].legend()

#acceleration vs height
axs[1,1].set_title("Acceleration vs height")
axs[1,1].plot(total_height, total_acceleration, color='cyan', label='Acceleration')
#axs[1,1].axhline(y=0, color='r', linestyle='--', label=f'Acceleration=0')
axs[1,1].axvline(x=height_braking, color='orange', linestyle='--', label='Magnetic braking')
axs[1,1].set_xlabel("Height (m)")
axs[1,1].set_ylabel("Acceleration (m/s²)")
axs[1,1].grid(True)
axs[1,1].set_xlim(y_i, 0)
axs[1,1].legend()

plt.show()