# -*- coding: utf-8 -*-
"""Challenge graphs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MESoyrawMpsC2uCP3gr3-Iv9g8ZEgF1R
"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f

"""#Load libraries"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

charge = 'https://raw.githubusercontent.com/cararm4073/tec-archive/refs/heads/main/university/EF26/F1013B/Charge.csv'
discharge = 'https://raw.githubusercontent.com/cararm4073/tec-archive/refs/heads/main/university/EF26/F1013B/Discharge.csv'

"""#Read data and create variables"""

ch = pd.read_csv(charge)
ds = pd.read_csv(discharge)

t1 = ch['Time'].values
c1 = ch['Voltage'].values

t2 = ds['Time'].values
c2 = ds['Voltage'].values

"""#Graphs"""

plt.figure(figsize=(10, 5))
plt.plot(t1, c1, 'b-', label='Capacitor charging')

plt.title('Time vs Capacitor charge')
plt.xlabel('Time (s)')
plt.ylabel('Capacitor charge (C)')
plt.grid(True)
plt.legend()
plt.show()

plt.figure(figsize=(10, 5))
plt.plot(t2, c2, 'r-', label='Capacitor discharging')

plt.title('Time vs Capacitor charge')
plt.xlabel('Time (s)')
plt.ylabel('Capacitor charge (C)')
plt.grid(True)
plt.legend()
plt.show()