# -*- coding: utf-8 -*-
"""Lab 3 - Mariotte bottle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/

#Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""#Measurements

##Diameters
"""

bottle = 6.0
hole = 0.4

"""##Areas"""

areaBottle = np.pi * (bottle/2)**2
areaHole = np.pi * (hole/2)**2
areas = areaBottle / areaHole

"""#Load files"""

v1 = 'https://raw.githubusercontent.com/cararm4073/tec-archive/refs/heads/main/university/EF26/F1008/Lab3/video1.csv'
v2 = 'https://raw.githubusercontent.com/cararm4073/tec-archive/refs/heads/main/university/EF26/F1008/Lab3/video2.csv'
v3 = 'https://raw.githubusercontent.com/cararm4073/tec-archive/refs/heads/main/university/EF26/F1008/Lab3/video3.csv'
v4 = 'https://raw.githubusercontent.com/cararm4073/tec-archive/refs/heads/main/university/EF26/F1008/Lab3/video4.csv'
v5 = 'https://raw.githubusercontent.com/cararm4073/tec-archive/refs/heads/main/university/EF26/F1008/Lab3/video5.csv'

"""##Data frames"""

df1 = pd.read_csv(v1)
df2 = pd.read_csv(v2, skiprows=1)
df3 = pd.read_csv(v3, skiprows=1)
df4 = pd.read_csv(v4)
df5 = pd.read_csv(v5, skiprows=1)

"""##Clear empty data and set variables"""

df1 = df1.dropna(subset=['t', 'y'])
t1 = df1['t'].values
y1 = df1['y'].values

df2 = df2.dropna(subset=['t', 'y'])
t2 = df2['t'].values
y2 = df2['y'].values

df3 = df3.dropna(subset=['t', 'y'])
t3 = df3['t'].values
y3 = df3['y'].values

df4 = df4.dropna(subset=['t', 'y'])
t4 = df4['t'].values
y4 = df4['y'].values

df5 = df5.dropna(subset=['t', 'y'])
t5 = df5['t'].values
y5 = df5['y'].values

"""#Maths

##Gradients
The actual derivatives for height or position y. Using the - sign as it decreases

Derivative of y position respect to time
"""

vLevel1 = -np.gradient(y1, t1)
vLevel2 = -np.gradient(y2, t2)
vLevel3 = -np.gradient(y3, t3)
vLevel4 = -np.gradient(y4, t4)
vLevel5 = -np.gradient(y5, t5)

"""##Output velocities
Or the efflux velocities
"""

vOut1 = vLevel1 * areas
vOut2 = vLevel2 * areas
vOut3 = vLevel3 * areas
vOut4 = vLevel4 * areas
vOut5 = vLevel5 * areas

"""-----
#Plots

##Overall plot
General plot with the 5 repetitions
"""

# @title Water level velocity vs time
plt.figure(figsize=(14, 5))
plt.plot(t1, vLevel1, 'b-', label='Video 1')
plt.plot(t2, vLevel2, 'g-', label='Video 2')
plt.plot(t3, vLevel3, 'r-', label='Video 3')
plt.plot(t4, vLevel4, 'm-', label='Video 4')
plt.plot(t5, vLevel5, 'y-', label='Video 5')

plt.title('Water level velocity vs Time')
plt.xlabel('Time (s)')
plt.ylabel('Water level velocity (cm/s)')
plt.grid(True)
plt.legend()
plt.show()

# @title Output velocity vs time
plt.figure(figsize=(14, 5))
plt.plot(t1, vOut1, 'b-', label='Video 1')
plt.plot(t2, vOut2, 'g-', label='Video 2')
plt.plot(t3, vOut3, 'r-', label='Video 3')
plt.plot(t4, vOut4, 'm-', label='Video 4')
plt.plot(t5, vOut5, 'y-', label='Video 5')

plt.title('Output velocity vs Time')
plt.xlabel('Time (s)')
plt.ylabel('Output velocity (cm/s)')
plt.grid(True)
plt.legend()
plt.show()

"""##1. Repetition 1"""

# @title Water level velocity vs time
plt.figure(figsize=(10, 5))
plt.plot(t1, vLevel1, 'b-', label='Video 1')
plt.title('Water level velocity vs Time')
plt.xlabel('Time (s)')
plt.ylabel('Water level velocity (cm/s)')
plt.grid(True)
plt.legend()
plt.show()

# @title Output velocity vs Time
plt.figure(figsize=(10, 5))
plt.plot(t1, vOut1, 'r-', label='Video 1')
plt.title('Output velocity vs Time')
plt.xlabel('Time (s)')
plt.ylabel('Output velocity (cm/s)')
plt.grid(True)
plt.legend()
plt.show()

"""##Repetition 2"""

# @title Water level velocity vs time
plt.figure(figsize=(10, 5))
plt.plot(t2, vLevel2, 'b-', label='Video 2')
plt.title('Water level velocity vs Time')
plt.xlabel('Time (s)')
plt.ylabel('Water level velocity (cm/s)')
plt.grid(True)
plt.legend()
plt.show()

# @title Output velocity vs Time
plt.figure(figsize=(10, 5))
plt.plot(t2, vOut2, 'r-', label='Video 2')
plt.title('Output velocity vs Time')
plt.xlabel('Time (s)')
plt.ylabel('Output velocity (cm/s)')
plt.grid(True)
plt.legend()
plt.show()

"""##Repetition 3"""

# @title Water level velocity vs time
plt.figure(figsize=(10, 5))
plt.plot(t3, vLevel3, 'b-', label='Video 3')
plt.title('Water level velocity vs Time')
plt.xlabel('Time (s)')
plt.ylabel('Water level velocity (cm/s)')
plt.grid(True)
plt.legend()
plt.show()

# @title Output velocity vs Time
plt.figure(figsize=(10, 5))
plt.plot(t3, vOut3, 'r-', label='Video 3')
plt.title('Output velocity vs Time')
plt.xlabel('Time (s)')
plt.ylabel('Output velocity (cm/s)')
plt.grid(True)
plt.legend()
plt.show()

"""##Repetition 4"""

# @title Water level velocity vs time
plt.figure(figsize=(10, 5))
plt.plot(t4, vLevel4, 'b-', label='Video 4')
plt.title('Water level velocity vs Time')
plt.xlabel('Time (s)')
plt.ylabel('Water level velocity (cm/s)')
plt.grid(True)
plt.legend()
plt.show()

# @title Output velocity vs Time
plt.figure(figsize=(10, 5))
plt.plot(t4, vOut4, 'r-', label='Video 4')
plt.title('Output velocity vs Time')
plt.xlabel('Time (s)')
plt.ylabel('Output velocity (cm/s)')
plt.grid(True)
plt.legend()
plt.show()

"""##Repetition 5"""

# @title Water level velocity vs time
plt.figure(figsize=(10, 5))
plt.plot(t5, vLevel5, 'b-', label='Video 5')
plt.title('Water level velocity vs Time')
plt.xlabel('Time (s)')
plt.ylabel('Water level velocity (cm/s)')
plt.grid(True)
plt.legend()
plt.show()

# @title Output velocity vs Time
plt.figure(figsize=(10, 5))
plt.plot(t5, vOut5, 'r-', label='Video 5')
plt.title('Output velocity vs Time')
plt.xlabel('Time (s)')
plt.ylabel('Output velocity (cm/s)')
plt.grid(True)
plt.legend()
plt.show()